#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p \
    /config/hooks

if [ ! -f "/config/hooks/hooks.json" ]; then
    cp /defaults/hooks.json /config/hooks/hooks.json
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config
fi
