#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-setuidgid abc /app/webhook \
            -hooks /config/hooks/hooks.json \
            -ip 0.0.0.0 ${EXTRA_PARAM:=-hotreload}
else
    exec \
        /app/webhook \
            -hooks /config/hooks/hooks.json \
            -ip 0.0.0.0 ${EXTRA_PARAM:=-hotreload}
fi
