#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2086

exec \
    s6-setuidgid abc webhook \
    -hooks /config/hooks/hooks.json \
    -ip 0.0.0.0 ${EXTRA_PARAM:=-hotreload}
