name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron: "6 * * * *"

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/check-and-release.yml@v6
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "webhook"
      release_type: "github"
      release_url: "https://api.github.com/repos/adnanh/webhook"
    secrets:
      repo_release_token: ${{ secrets.repo_release_token }}
